# Generated by Django 4.1.6 on 2023-02-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacidad_Megas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megas', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Mega',
                'verbose_name_plural': 'Megas',
                'db_table': 'Megas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=13, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono_uno', models.CharField(blank=True, max_length=13, null=True)),
                ('telefonos_dos', models.CharField(blank=True, max_length=13, null=True)),
                ('mensualidad', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=25, null=True)),
                ('estado', models.CharField(blank=True, choices=[('arriba', 'Activo'), ('abajo', 'Sin servicio')], max_length=13, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cap_megas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.capacidad_megas')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'db_table': 'Detalle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equi', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'Equipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMunicipio', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'Municipio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ins', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo_Instalacion',
                'verbose_name_plural': 'Tipos_Instalaciones',
                'db_table': 'Tipo_Instalacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Tipo_Pago',
                'verbose_name_plural': 'Tipos_Pagos',
                'db_table': 'Tipo_Pago',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.detalle')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.tipo_pago')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='equipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.equipos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.municipio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.tipo_instalacion'),
        ),
    ]
