# Generated by Django 4.1.7 on 2023-04-11 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ap',
            fields=[
                ('nombreAp', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Ap',
                'verbose_name_plural': 'Ap',
                'db_table': 'Ap',
                'ordering': ['nombreAp'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=80)),
                ('telefono_uno', models.CharField(blank=True, max_length=13, null=True)),
                ('telefonos_dos', models.CharField(blank=True, max_length=13, null=True)),
                ('valor_instalacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=25, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Activos', 'Activos'), ('Suspendidos', 'Suspendidos'), ('REquipos', 'REquipos'), ('Retiros', 'Retiros')], max_length=13, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cap_megas', models.CharField(blank=True, max_length=25, null=True)),
                ('ap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.ap')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'ordering': ['ip'],
            },
        ),
        migrations.CreateModel(
            name='ClienteRetirado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('telefono_uno', models.CharField(blank=True, max_length=13, null=True)),
                ('telefonos_dos', models.CharField(blank=True, max_length=13, null=True)),
                ('valor_instalacion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=25, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Activos', 'Activos'), ('Suspendidos', 'Suspendidos'), ('REquipos', 'REquipos'), ('Retiros', 'Retiros')], max_length=13, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cap_megas', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_retirado', models.DateField(auto_now_add=True, null=True)),
                ('ap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.ap')),
            ],
            options={
                'verbose_name': 'Cliente_Retirado',
                'verbose_name_plural': 'Clientes_Retirados',
                'db_table': 'Cliente_Retirado',
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'db_table': 'Detalle',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('nombre_equi', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'Equipo',
                'ordering': ['nombre_equi'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('nombreMunicipio', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'Municipio',
                'ordering': ['nombreMunicipio'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('nombre_tecnico', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Nombre Tecnico',
                'verbose_name_plural': 'Nombres del Tecnico',
                'db_table': 'Nombre del tecnico',
                'ordering': ['nombre_tecnico'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Instalacion',
            fields=[
                ('tipo_ins', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tipo_Instalacion',
                'verbose_name_plural': 'Tipos_Instalaciones',
                'db_table': 'Tipo_Instalacion',
                'ordering': ['tipo_ins'],
            },
        ),
        migrations.CreateModel(
            name='FacturaRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(blank=True, choices=[('Mensualidad', 'Mensualidad'), ('Banco', 'Banco'), ('Acertemos', 'Acertemos')], max_length=15, null=True)),
                ('valor_pago', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago (Opcional)')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento (Opcional)')),
                ('cliente_retirado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.clienteretirado')),
                ('detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.detalle')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(blank=True, choices=[('#Recibo', '#Recibo'), ('Bancos', 'Bancos'), ('Acertemos', 'Acertemos'), ('Nequi', 'Nequi')], max_length=15, null=True)),
                ('valor_pago', models.CharField(blank=True, max_length=15, null=True)),
                ('n_recibo', models.CharField(blank=True, max_length=6, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago (Opcional)')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento (Opcional)')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
                ('detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.detalle')),
            ],
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='equipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.equipos'),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.municipio'),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='nombre_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.tecnico'),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='tipo_instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.tipo_instalacion'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='equipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.equipos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.municipio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.tecnico'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.tipo_instalacion'),
        ),
    ]
