# Generated by Django 4.1.6 on 2023-02-09 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteRetirado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=13)),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono_uno', models.CharField(max_length=13, null=True)),
                ('telefonos_dos', models.CharField(max_length=13, null=True)),
                ('mensualidad', models.CharField(max_length=15, null=True)),
                ('fecha_instalacion', models.DateField(null=True)),
                ('direccion', models.CharField(max_length=25, null=True)),
                ('estado', models.CharField(choices=[('arriba', 'Activo'), ('abajo', 'Sin servicio')], max_length=13, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('fecha_eliminacion', models.DateField(default=django.utils.timezone.now)),
                ('cap_megas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.capacidad_megas')),
                ('equipos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.equipos')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.municipio')),
                ('tipo_instalacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.tipo_instalacion')),
            ],
            options={
                'verbose_name': 'Cliente_Retirado',
                'verbose_name_plural': 'Clientes_Retirados',
                'db_table': 'Cliente_Retirado',
                'ordering': ['ip'],
            },
        ),
    ]
