# Generated by Django 4.1.7 on 2023-03-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Tipo_Pago',
                'verbose_name_plural': 'Tipos_Pagos',
                'db_table': 'Tipo_Pago',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='facturaretirada',
            name='cliente_retirado',
        ),
        migrations.AddField(
            model_name='facturaretirada',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago (Opcional)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento (Opcional)'),
        ),
        migrations.AlterField(
            model_name='facturaretirada',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago (Opcional)'),
        ),
        migrations.AlterField(
            model_name='facturaretirada',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento (Opcional)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.tipo_pago'),
        ),
        migrations.AlterField(
            model_name='facturaretirada',
            name='tipo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.tipo_pago'),
        ),
    ]
