# Generated by Django 4.1.7 on 2023-03-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, choices=[('Activos', 'Activos'), ('Suspendidos', 'Suspendidos'), ('REquipos', 'REquipos'), ('Retiros', 'Retiros')], max_length=13, null=True),
        ),
    ]
