# Generated by Django 4.1.7 on 2023-03-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaretirada',
            old_name='cliente_retirado',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago (Opcional)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento (Opcional)'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('Mensualidad', 'Mensualidad'), ('Banco', 'Banco'), ('Acertemos', 'Acertemos')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='facturaretirada',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago (Opcional)'),
        ),
        migrations.AlterField(
            model_name='facturaretirada',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento (Opcional)'),
        ),
        migrations.AlterField(
            model_name='facturaretirada',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('Mensualidad', 'Mensualidad'), ('Banco', 'Banco'), ('Acertemos', 'Acertemos')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Tipo_Pago',
        ),
    ]
