# Generated by Django 4.1.7 on 2023-03-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_tipo_pago_remove_facturaretirada_cliente_retirado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('Mensualidad', 'Mensualidad'), ('Banco', 'Banco'), ('Acertemos', 'Acertemos')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='facturaretirada',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('Mensualidad', 'Mensualidad'), ('Banco', 'Banco'), ('Acertemos', 'Acertemos')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Tipo_Pago',
        ),
    ]
