# Generated by Django 4.1.6 on 2023-02-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_clienteretirado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienteretirado',
            options={'verbose_name': 'Cliente_Retirado', 'verbose_name_plural': 'Clientes_Retirados'},
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='cap_megas',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='equipos',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='fecha_eliminacion',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='fecha_instalacion',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='mensualidad',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='telefono_uno',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='telefonos_dos',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='tipo_instalacion',
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='fecha_retiro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
