# Generated by Django 4.1.7 on 2023-03-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ap',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='ap',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
