# Generated by Django 4.1.7 on 2023-03-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_cliente_retirado_facturaretirada_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaretirada',
            name='cliente',
        ),
        migrations.AddField(
            model_name='facturaretirada',
            name='cliente_retirado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.clienteretirado'),
        ),
        migrations.AlterField(
            model_name='clienteretirado',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clienteretirado',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='clienteretirado',
            name='ip',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='clienteretirado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
