# Generated by Django 4.1.7 on 2023-03-17 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente_ap_clienteretirado_ap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAp', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Ap',
                'verbose_name_plural': 'Ap',
                'db_table': 'Ap',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.ap'),
        ),
        migrations.AlterField(
            model_name='clienteretirado',
            name='ap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.ap'),
        ),
    ]
