# Generated by Django 4.1.6 on 2023-02-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_clienteretirado_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteretirado',
            old_name='fecha_retiro',
            new_name='fecha_retirado',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='cliente',
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='cap_megas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.capacidad_megas'),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='direccion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='equipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.equipos'),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='estado',
            field=models.CharField(blank=True, choices=[('arriba', 'Activo'), ('abajo', 'Sin servicio')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='ip',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='mensualidad',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.municipio'),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='telefono_uno',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='telefonos_dos',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='tipo_instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.tipo_instalacion'),
        ),
    ]
