# Generated by Django 4.1.7 on 2023-03-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_factura_n_recibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='mensualidad',
        ),
        migrations.RemoveField(
            model_name='clienteretirado',
            name='mensualidad',
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_instalacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clienteretirado',
            name='valor_instalacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cap_megas',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='clienteretirado',
            name='cap_megas',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Capacidad_Megas',
        ),
    ]
