# Generated by Django 4.1.6 on 2023-02-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_factura_cliente_alter_factura_detalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cap_megas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.capacidad_megas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='equipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.equipos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.municipio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.tipo_instalacion'),
        ),
        migrations.AlterField(
            model_name='clienteretirado',
            name='cap_megas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.capacidad_megas'),
        ),
        migrations.AlterField(
            model_name='clienteretirado',
            name='equipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.equipos'),
        ),
        migrations.AlterField(
            model_name='clienteretirado',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.municipio'),
        ),
        migrations.AlterField(
            model_name='clienteretirado',
            name='tipo_instalacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.tipo_instalacion'),
        ),
        migrations.CreateModel(
            name='FacturaRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
                ('detalle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.detalle')),
                ('tipo_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.tipo_pago')),
            ],
        ),
    ]
