# Generated by Django 4.1.6 on 2023-02-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_facturaretirada_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaretirada',
            old_name='cliente',
            new_name='cliente_retirado',
        ),
    ]
